-   id: eslint
    name: eslint
    description: ''
    entry: eslint
    language: node
    'types': [javascript]
    args: [--fix]
    require_serial: false
    additional_dependencies: ["eslint@8.45.0"]
    minimum_pre_commit_version: '0'
